# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CortexMemory < Formula
  desc "Import-first, observable memory layer for AI agents. Memory that forgets."
  homepage "https://github.com/hurttlocker/cortex"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hurttlocker/cortex/releases/download/v1.2.0/cortex-darwin-amd64.tar.gz"
      sha256 "0420cb77a0f180949256b35bbd1942c5e369e67fe168ced445650e66d8a7aee8"

      define_method(:install) do
        bin.install "cortex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hurttlocker/cortex/releases/download/v1.2.0/cortex-darwin-arm64.tar.gz"
      sha256 "0866e6ab8194941118e7496e4fbbdb0f214ecbfb1f7f976dfcd85c4b01eb0857"

      define_method(:install) do
        bin.install "cortex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hurttlocker/cortex/releases/download/v1.2.0/cortex-linux-amd64.tar.gz"
      sha256 "6d7f7551c3d48acfd31a4c0c2268fad5eef342b5a6befa973d7319c5a6b44803"
      define_method(:install) do
        bin.install "cortex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hurttlocker/cortex/releases/download/v1.2.0/cortex-linux-arm64.tar.gz"
      sha256 "98efc62581175f74cf3d78b8e996377a108470e253e5c00c186eb85b4966f86e"
      define_method(:install) do
        bin.install "cortex"
      end
    end
  end

  def caveats
    <<~EOS
      Cortex is installed! Quick start:

        # Import some files
        cortex import ~/notes/ --recursive --extract

        # Search your memory
        cortex search "what did I decide about..."

        # Run as MCP server (for Claude Code, etc.)
        cortex mcp

      Data stored in: ~/.cortex/cortex.db
    EOS
  end

  test do
    system "#{bin}/cortex", "version"
  end
end
