# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CortexMemory < Formula
  desc "Import-first, observable memory layer for AI agents. Memory that forgets."
  homepage "https://github.com/hurttlocker/cortex"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hurttlocker/cortex/releases/download/v1.3.0/cortex-darwin-amd64.tar.gz"
      sha256 "6e3d0b32b6a0e29f3cd0ea45b3df4710a06c49ff4c4f66b07f23c206277a2799"

      define_method(:install) do
        bin.install "cortex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hurttlocker/cortex/releases/download/v1.3.0/cortex-darwin-arm64.tar.gz"
      sha256 "7670bb9ca5c43f3bde271df3b53b8384806861a599f4458bab321687f1cab44a"

      define_method(:install) do
        bin.install "cortex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hurttlocker/cortex/releases/download/v1.3.0/cortex-linux-amd64.tar.gz"
      sha256 "c139caf60d6da62eece8b4565d487ca52bf4b61109f6284a67fc4943c9c942ad"
      define_method(:install) do
        bin.install "cortex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hurttlocker/cortex/releases/download/v1.3.0/cortex-linux-arm64.tar.gz"
      sha256 "240988f63f39951cbf7df768437520c4b8ea08393befd1a40ba19cd81e4d89bb"
      define_method(:install) do
        bin.install "cortex"
      end
    end
  end

  def caveats
    <<~EOS
      Cortex is installed! Quick start:

        # Import some files
        cortex import ~/notes/ --recursive --extract

        # Search your memory
        cortex search "what did I decide about..."

        # Run as MCP server (for Claude Code, etc.)
        cortex mcp

      Data stored in: ~/.cortex/cortex.db
    EOS
  end

  test do
    system "#{bin}/cortex", "version"
  end
end
